### ISSUE TITLE
exerslide serve error

### ISSUE THREAD

**Issue by todrobbins** [facebookincubator/exerslide#24]
I followed the installation instructions and successfully ran `exerslide init`, but when I try to run `exerslide serve` I get this error seemingly related to `webpack`:

```
test ➜ exerslide serve
module.js:491
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/todrobbins/dev/test/node_modules/exerslide/lib/builder.js:24:17)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```

Just for context, I have version 3.5.6 of `webpack` installed.

**Comment by fkling** [comment]
Installed where? Exerslide still uses webpack v1. How does the folder look like after you ran `exerslide init`? Similar as the [example folder](https://github.com/facebookincubator/exerslide/tree/1670018b7f82fae3e0f895474eb82bd8615acfc6/example)?

The error suggests that webpack wasn't installed (locally). If it seems like all the files are here, you could try running `npm install` in the project folder.

**Comment by todrobbins** [comment]
I meant that I installed the CLI and webpack globally.

This is the output I get when I `npm install`:

```
exerslide-test ➜ npm install
npm WARN exerslide@1.1.5 requires a peer of codemirror@^5.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN exerslide@1.1.5 requires a peer of highlight.js@^9.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN exerslide@1.1.5 requires a peer of react@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN exerslide@1.1.5 requires a peer of react-dom@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN exerslide@1.1.5 requires a peer of webpack@^1.12.11 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-server@1.16.5 requires a peer of webpack@>=1.3.0 <3 but none is installed. You must install peer dependencies yourself.
npm WARN exerslide-test No description
npm WARN exerslide-test No repository field.
npm WARN exerslide-test No license field.

up to date in 2.536s
```

**Comment by todrobbins** [comment]
PS: when I run `exerslide init` I get this output:

```
test ➜ exerslide init
Installing exerslide (`npm install exerslide`). This may take a while...
Creating initial files...
Copied "webpack.config.js".
Copied "slides/00-example.md".
Copied "references.yml".
? It seems you edited "package.json".
Copying would remove your changes. What do you want to do?
  1) Keep your file
  2) Keep all your files
  3) Overwrite
  4) Overwrite all
  5) Show diff
  6) Edit diff
  Answer:
```

Which option is correct?

**Comment by william-abboud** [comment]
Its almost a year after your comment Tod but the correct option which worked for me is 4)

**Comment by todrobbins** [comment]
Working for me now. Thanks for reminding me!
