### ISSUE TITLE
Exerslide not working under Windows

### ISSUE THREAD

**Issue by tmair** [facebookincubator/exerslide#8]
I am running into serveral issues trying to run exerslide under Windows. I will try to report the issues I ran into:
- The use of `process_child` only works correctly under UNIX systems. An alternative would be to use `cross-spawn`
- The various scripts for linting an building the package only work on UNIX systems. This prevents me from contributing fixes as I am not able to run the tests or the linter properly

**Comment by fkling** [comment]
😞  

Unfortunately I don't have access to a Windows machine, so it's not possible for me to test any changes wrt that.

If you or someone else who has Windows can try to get it to work, I'd appreciate it! Could you provide more detailed information about the issue, like error output and steps to reproduce?

**Comment by tmair** [comment]
I will try and solve some of the issues. 

Could you tell me how one is supposed to set up the dev environment on a UNIX system?

**Comment by fkling** [comment]
What specifically do you want to know? Other than installing Node ([nvm](https://github.com/creationix/nvm) can help with that) and cloning the repo, there is not really anything to do I think.

**Comment by tmair** [comment]
As there are multiple packages included in the repo, how do you test if the different packages work  before pushing them npm?

The reason I am asking is that I am trying to figure out how I am going to test changes during developement, when trying to solve the issues on Windows.

**Comment by fkling** [comment]
Ah I see.... that's what `scripts/setupDevEnv.js` is for, but since it uses `child_process` itself it may not work Windows either.

Basically what it does, given a target folder, lets say `myPresentation/`:
1. Install all peer dependencies listed in `packages/**/package.json` _globally_.
2. Go through all packages in `packages/`, link their peer dependencies and link the packages themselves (which makes them globally available as well)
3. Link `packages/exerslide/` into `myPresentation/`.
4. Run `exerslide copy-defaults` to initialize the project.
5. Install dependencies after removing exerslide packages and packages from step 1 from `package.json`.
6. Link all exerslide dependencies and packages from step 1.

**Comment by tmair** [comment]
Ok thanks, that helps. 

I did not try it yet, but I guess the issue with the `child_process` can be solved relatively easy. 

Is started to work on some changes to support windows and I am having quite a few issues with symbolic links on windows since they are only allowed if a process runs with administrator permissions. Right now I don't really know how to handle that. In the meantime I will try to work around that issue.

If you want to have a look at my progress you can check https://github.com/tmair/exerslide/tree/windows-support

**Comment by g-nr** [comment]
when installing following error shows
`exerslide init p1
Installing exerslide (`npm install exerslide`). This may take a while...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:1036:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3`

**Comment by mcking65** [comment]
@nagarajgumpini, that is my experience as well with version 1.1.0. 

@tmair, it would be a feasible work-around for me, at least, to run at an admin command prompt. Hoping you are making some progress. I am anxious to be able to use on Windows. And, ... THANK YOU for contributing!!

**Comment by fkling** [comment]
Maybe @rubengees can share their setup, since they seem to have had to problem with `exerslide init` at least.

**Comment by rubengees** [comment]
We sadly couldn't get it to work. There was another error which was to complex for us to fix.
Everybody switched to Linux or a VM for our presentation or until windows support is here...

**Comment by fkling** [comment]
Uh ok 😞 Sorry for the inconvenience! I have a colleague who uses Windows and wants to user exerslide, so hopefully we will be able to figure it out together, but that will take a while.

In the meantime, please continue to provide detail bug reports and fixes.

Sorry again!

**Comment by rubengees** [comment]
Okay here goes:

After applying #13 locally, the presentation actually builds and serves, but crashes in the browser with the following stacktrace:

```
Uncaught TypeError: $export is not a function
    at Object.<anonymous> (http://localhost:8080/app.js?779c72bc670fda362e99:1475:2)
    at __webpack_require__ (http://localhost:8080/app.js?779c72bc670fda362e99:20:30)
    at Object.<anonymous> (http://localhost:8080/app.js?779c72bc670fda362e99:1458:2)
    at __webpack_require__ (http://localhost:8080/app.js?779c72bc670fda362e99:20:30)
    at Object.<anonymous> (http://localhost:8080/app.js?779c72bc670fda362e99:1447:32)
    at __webpack_require__ (http://localhost:8080/app.js?779c72bc670fda362e99:20:30)
    at Object.<anonymous> (http://localhost:8080/app.js?779c72bc670fda362e99:1415:24)
    at __webpack_require__ (http://localhost:8080/app.js?779c72bc670fda362e99:20:30)
    at Object.<anonymous> (http://localhost:8080/app.js?779c72bc670fda362e99:1397:11)
    at __webpack_require__ (http://localhost:8080/app.js?779c72bc670fda362e99:20:30)
(anonymous function) @ app.js?779c72b…:1475
__webpack_require__ @ app.js?779c72b…:20
(anonymous function) @ app.js?779c72b…:1458
__webpack_require__ @ app.js?779c72b…:20
(anonymous function) @ app.js?779c72b…:1447
__webpack_require__ @ app.js?779c72b…:20
(anonymous function) @ app.js?779c72b…:1415
__webpack_require__ @ app.js?779c72b…:20
(anonymous function) @ app.js?779c72b…:1397
__webpack_require__ @ app.js?779c72b…:20
(anonymous function) @ app.js?779c72b…:1265
__webpack_require__ @ app.js?779c72b…:20
(anonymous function) @ app.js?779c72b…:1241
__webpack_require__ @ app.js?779c72b…:20
(anonymous function) @ app.js?779c72b…:930
__webpack_require__ @ app.js?779c72b…:20
(anonymous function) @ app.js?779c72b…:914
__webpack_require__ @ app.js?779c72b…:20
(anonymous function) @ app.js?779c72b…:903
__webpack_require__ @ app.js?779c72b…:20
(anonymous function) @ app.js?779c72b…:201
__webpack_require__ @ app.js?779c72b…:20
(anonymous function) @ app.js?779c72b…:61
(anonymous function) @ app.js?779c72b…:190
__webpack_require__ @ app.js?779c72b…:20
(anonymous function) @ app.js?779c72b…:50
__webpack_require__ @ app.js?779c72b…:20
(anonymous function) @ app.js?779c72b…:40
(anonymous function) @ app.js?779c72b…:43
```

I have no idea what is going on here...

**Comment by cristian-sima** [comment]
Same problem here.

Os: Windows 10 x64 Pro
Node: v6.3.1

I created a new Github project, created a folder `myPresentation` then run the code:

![image](https://cloud.githubusercontent.com/assets/12199042/22065190/c0e94416-dd8f-11e6-9d64-2bb3b2928f5e.png)
